name          'puppet-softwarecollectionsorg'
version       '0.2.0'
source        'UNKNOWN'
author        'smerrill'
license       'Apache License, Version 2.0'
summary       'Add Software Collections from softwarecollections.org.'
description   'A quick way to add Software Collections from softwarecollections.org to a Fedora or RHEL/CentOS system.'
project_page  'https://github.com/smerrill/puppet-softwarecollectionsorg'

dependency 'puppetlabs/stdlib'
